import {
	faThumbsDown,
	faThumbsUp,
	faHourglassStart,
	faClock,
	faTruck
} from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import type { NextPage, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { getByCity } from '../features/productsGetter';
import ColList from '../components/columnList';
import Companies from '../components/companiesList';
import { useState } from 'react';

const pageLinks = ['Nya', 'Populara'];

const Home = ({
	products,
	hotProducts
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
	const [pageNav, setPageNav] = useState(pageLinks[0]);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				<div className='bg-white mb-3 '>
					<div className=' lg:container text-sm py-3'>
						{pageLinks.map((item, index) => {
							return (
								<button
									key={index}
									onClick={() => {
										setPageNav(item);
									}}
									className={
										pageNav === item
											? 'p-2 underline underline-offset-8 text-sky-900 font-bold mx-1 rounded'
											: 'p-2 no-underline text-sky-900 font-bold mx-1 rounded'
									}>
									{item}
								</button>
							);
						})}
					</div>
				</div>
				<div className='lg:container  lg:flex  '>
					<div className='lg:basis-4/5 '>
						<ul className='p-2 lg:p-0 lg:mr-2'>
							{products.map((i: any, index: number) => {
								return (
									<Link href={'/singelProduct'} passHref key={index}>
										<a>
											<div className='bg-white  my-2 py-1 rounded shadow-lg  '>
												<div className='flex justify-between px-2 md:hidden  '>
													<div className='flex p-2 w-28 justify-center items-center '>
														<button className='flex mr-5'>
															<FontAwesomeIcon
																icon={faThumbsUp}
																className='h-5 w-5 mr-1 text-sky-900'
															/>
															<span className='text-sm '>{i.likes}</span>
														</button>
														<button className='flex'>
															<FontAwesomeIcon
																icon={faThumbsDown}
																className='h-5 w-5 mt-[0.33rem] mr-1  text-sky-900'
															/>
															<span className='text-sm '>{i.dislikes}</span>
														</button>
													</div>
													<div className='flex p-3'>
														<p className='flex '>
															<FontAwesomeIcon
																icon={faHourglassStart}
																className='h-4 w-4 mr-[2px] mt-[2px] text-sky-900'
															/>
															<span className='text-sm '>{i.expires}</span>
														</p>
														<p className='flex ml-3'>
															<FontAwesomeIcon
																icon={faClock}
																className='h-4 w-4 mr-[4px] mt-[2px] text-sky-900'
															/>
															<span className='text-sm '>{i.added}</span>
														</p>
													</div>
												</div>
												<div className='flex py-1 '>
													<div className='basis-1/5  flex items-center   '>
														<div className='relative w-20 h-20 md:w-36 md:h-36  mx-auto'>
															<Image src={i.images[0]} alt='sr' layout='fill' />
														</div>
													</div>
													<div className='basis-4/5 pl-5 '>
														<div className='hidden md:flex md:justify-between '>
															<div className='flex p-2  items-center justify-center '>
																<button className='flex mr-5'>
																	<FontAwesomeIcon
																		icon={faThumbsUp}
																		className='h-5 w-5 text-sky-900 mr-1 '
																	/>
																	<span className='md:-mt-[2px]'>
																		{i.likes}
																	</span>
																</button>
																<button className='flex'>
																	<FontAwesomeIcon
																		icon={faThumbsDown}
																		className='h-5 w-5 text-sky-900 mt-1 mr-1 '
																	/>
																	<span className=' md:-mt-[2px]'>
																		{i.dislikes}
																	</span>
																</button>
															</div>
															<div className='flex p-2  '>
																<p className='flex items-center '>
																	<FontAwesomeIcon
																		icon={faHourglassStart}
																		className='h-5 w-5 text-sky-900 mr-[2px] '
																	/>
																	<span className=''>{i.expires}</span>
																</p>
																<p className='flex items-center ml-3'>
																	<FontAwesomeIcon
																		icon={faClock}
																		className='h-5 w-5 mr-[4px] text-sky-900 '
																	/>
																	<span className=''>{i.added}</span>
																</p>
															</div>
														</div>

														<div className='text-sm md:text-base md:mt-1 '>
															<p className='font-bold text-sky-900  '>
																{i.title}
															</p>

															<p className='flex  my-2 md:my-1'>
																<span className='font-bold text-sky-900 '>
																	{i.newPrice}
																	kr
																</span>
																<span className='mx-5  text-red-600 line-through'>
																	{i.lastPrice}
																	kr
																</span>
																<span className='flex text-slate-500'>
																	<FontAwesomeIcon
																		icon={faTruck}
																		className='h-5 w-5 md:mt-[2px]'
																	/>
																	{i.leverans}
																	kr
																</span>
															</p>
															<p className=' text-slate-500 '>
																Rabatter:
																<span className='ml-1 text-sky-900 font-bold '>
																	Careffour{' '}
																</span>
															</p>
															<p className=' hidden text-sm pt-2 pr-1 md:block  '>
																{`${i.description.substr(0, 200)}...`}
															</p>

															<div className='hidden px-1 my-3 md:block md:text-right'>
																<button className='border-2 border-sky-900 text-sky-900 hover:border-slate-300 w-28 md:mr-2 mr-1  p-1 rounded '>
																	{' '}
																	Save{' '}
																</button>
																<button className='bg-sky-900 hover:bg-sky-700 text-white w-28  p-1 rounded '>
																	See deal
																</button>
															</div>
														</div>
													</div>
												</div>
												<div className='md:hidden my-3'>
													<p className='text-sm p-2'>
														{`${i.description.substr(0, 200)}...`}
													</p>
												</div>
												<div className='flex justify-around px-1 my-1 md:hidden md:text-right'>
													<button className='border-2 border-sky-900 text-sky-900 hover:border-slate-300 w-28  md:mr-2 mr-1  p-1 rounded '>
														{' '}
														Save{' '}
													</button>
													<button className='bg-sky-900 hover:bg-sky-700 text-white w-28 p-1 rounded '>
														See deal
													</button>
												</div>
											</div>
										</a>
									</Link>
								);
							})}
						</ul>
					</div>
					<div className='hidden mt-2 lg:block basis-1/5'>
						<ColList products={hotProducts} />
						<Companies />
					</div>
				</div>
			</div>
		</div>
	);
};

export const getServerSideProps = async () => {
	const products = await getByCity('');
	const hotProducts = products.slice(0, 4);
	return {
		props: { products, hotProducts }
	};
};

export default Home;
